//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenu
    {
        public int AppMenuId { get; set; }
        public Nullable<int> moduleID { get; set; }
        public string MenuName { get; set; }
        public string Description { get; set; }
        public string Tooltip { get; set; }
        public string DivName { get; set; }
        public string PageName { get; set; }
        public string MenuUrl { get; set; }
        public string ShowTarget { get; set; }
        public string icon { get; set; }
        public Nullable<bool> ShowInBar { get; set; }
        public Nullable<bool> IsToolbar { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
