//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigureModel
    {
        public int Id { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public bool IsSadmin { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> moduleID { get; set; }
        public System.DateTime IDate { get; set; }
    }
}
