//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLocatorMaster
    {
        public int mLocatorMasterId { get; set; }
        public Nullable<int> mWarehouseMasterId { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public string WarehouseCode { get; set; }
        public string AisleNo { get; set; }
        public string RackNo { get; set; }
        public string ShelfNo { get; set; }
        public string BinNo { get; set; }
        public string InputArea { get; set; }
        public string PackingArea { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
