//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EricssonDBEntities : DbContext
    {
        public EricssonDBEntities()
            : base("name=EricssonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<ConfigureModel> ConfigureModels { get; set; }
        public virtual DbSet<DepartMent> DepartMents { get; set; }
        public virtual DbSet<HexaModule> HexaModules { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<mActivity> mActivities { get; set; }
        public virtual DbSet<mAgency> mAgencies { get; set; }
        public virtual DbSet<mDesignation> mDesignations { get; set; }
        public virtual DbSet<mFloorMaster> mFloorMasters { get; set; }
        public virtual DbSet<mGroupMaster> mGroupMasters { get; set; }
        public virtual DbSet<mIndooMap> mIndooMaps { get; set; }
        public virtual DbSet<mIteamMaster> mIteamMasters { get; set; }
        public virtual DbSet<mIteamTypeMaster> mIteamTypeMasters { get; set; }
        public virtual DbSet<mLocationMaster> mLocationMasters { get; set; }
        public virtual DbSet<mLocatorMaster> mLocatorMasters { get; set; }
        public virtual DbSet<mMailConfig> mMailConfigs { get; set; }
        public virtual DbSet<mMaintenanceType> mMaintenanceTypes { get; set; }
        public virtual DbSet<mReader> mReaders { get; set; }
        public virtual DbSet<mReaderSettup> mReaderSettups { get; set; }
        public virtual DbSet<mRoomMaster> mRoomMasters { get; set; }
        public virtual DbSet<mSetDistance> mSetDistances { get; set; }
        public virtual DbSet<mShift> mShifts { get; set; }
        public virtual DbSet<mSiteMaster> mSiteMasters { get; set; }
        public virtual DbSet<mSkillCategory> mSkillCategories { get; set; }
        public virtual DbSet<mStatusMaster> mStatusMasters { get; set; }
        public virtual DbSet<mSupplier> mSuppliers { get; set; }
        public virtual DbSet<mUnitMaster> mUnitMasters { get; set; }
        public virtual DbSet<mVendor> mVendors { get; set; }
        public virtual DbSet<mWarehouseMaster> mWarehouseMasters { get; set; }
        public virtual DbSet<mWorkCategory> mWorkCategories { get; set; }
        public virtual DbSet<mZone> mZones { get; set; }
        public virtual DbSet<OrgInfo> OrgInfoes { get; set; }
        public virtual DbSet<RoleAcess> RoleAcesses { get; set; }
        public virtual DbSet<RoleMenu> RoleMenus { get; set; }
        public virtual DbSet<Rolemodule> Rolemodules { get; set; }
        public virtual DbSet<tAssetCheckOut> tAssetCheckOuts { get; set; }
        public virtual DbSet<tAssetMonitor> tAssetMonitors { get; set; }
        public virtual DbSet<tAssetStockIn> tAssetStockIns { get; set; }
        public virtual DbSet<tAssetStockIssue> tAssetStockIssues { get; set; }
        public virtual DbSet<tAssetStockTranfer> tAssetStockTranfers { get; set; }
        public virtual DbSet<tAssetTag> tAssetTags { get; set; }
        public virtual DbSet<TC_Action> TC_Action { get; set; }
        public virtual DbSet<TC_Customer> TC_Customer { get; set; }
        public virtual DbSet<TC_EmailConfiguration> TC_EmailConfiguration { get; set; }
        public virtual DbSet<TC_InquiryGroupSource> TC_InquiryGroupSource { get; set; }
        public virtual DbSet<TC_InquirySource> TC_InquirySource { get; set; }
        public virtual DbSet<TC_InquiryStatus> TC_InquiryStatus { get; set; }
        public virtual DbSet<TC_InquiryType> TC_InquiryType { get; set; }
        public virtual DbSet<TC_Lead> TC_Lead { get; set; }
        public virtual DbSet<TC_LeadDisposition> TC_LeadDisposition { get; set; }
        public virtual DbSet<TC_LeadFollowUp> TC_LeadFollowUp { get; set; }
        public virtual DbSet<TC_LeadStage> TC_LeadStage { get; set; }
        public virtual DbSet<TC_LeadSubDisposition> TC_LeadSubDisposition { get; set; }
        public virtual DbSet<TC_LeadType> TC_LeadType { get; set; }
        public virtual DbSet<tEmployeeTag> tEmployeeTags { get; set; }
        public virtual DbSet<tExtendWarranty> tExtendWarranties { get; set; }
        public virtual DbSet<tMaintenance> tMaintenances { get; set; }
        public virtual DbSet<toCategoryMaster> toCategoryMasters { get; set; }
        public virtual DbSet<toMonitor> toMonitors { get; set; }
        public virtual DbSet<toRFIDType> toRFIDTypes { get; set; }
        public virtual DbSet<toSupplier> toSuppliers { get; set; }
        public virtual DbSet<toSupplierCategory> toSupplierCategories { get; set; }
        public virtual DbSet<toSupplierType> toSupplierTypes { get; set; }
        public virtual DbSet<toToolMaintenance> toToolMaintenances { get; set; }
        public virtual DbSet<toToolStockIn> toToolStockIns { get; set; }
        public virtual DbSet<toTooltag> toTooltags { get; set; }
        public virtual DbSet<toTrackInfo> toTrackInfoes { get; set; }
        public virtual DbSet<tPortChangeLog> tPortChangeLogs { get; set; }
        public virtual DbSet<tReaderLog> tReaderLogs { get; set; }
        public virtual DbSet<tRFIDType> tRFIDTypes { get; set; }
        public virtual DbSet<tSpeedTrack> tSpeedTracks { get; set; }
        public virtual DbSet<tToolTrackDemo> tToolTrackDemoes { get; set; }
        public virtual DbSet<tTrackInfo> tTrackInfoes { get; set; }
    }
}
