//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRoomMaster
    {
        public int mRoomMasterId { get; set; }
        public Nullable<int> mFloorMasterId { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public Nullable<int> mSiteMasterId { get; set; }
        public Nullable<int> mZoneId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
