//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mVendor
    {
        public int mVendorId { get; set; }
        public string VendorName { get; set; }
        public string ContactName { get; set; }
        public string GSTIN { get; set; }
        public string PAN { get; set; }
        public string TIN { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public Nullable<int> StateID { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
