//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssetTag
    {
        public int tAssetTagId { get; set; }
        public Nullable<int> mIteamMasterId { get; set; }
        public string IteamName { get; set; }
        public string IteamCode { get; set; }
        public string IteamDescription { get; set; }
        public string UID { get; set; }
        public string RFID { get; set; }
        public string BarCode { get; set; }
        public string SerialNo { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> mVendorId { get; set; }
        public Nullable<decimal> PurchaseCost { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string InvNo { get; set; }
        public Nullable<int> Depreciation { get; set; }
        public Nullable<int> mStatusMasterId { get; set; }
        public Nullable<int> tEmployeeTagId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Receivedby { get; set; }
        public Nullable<int> DefaultWarranty { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> bStock { get; set; }
        public Nullable<int> mUnitMasterId { get; set; }
        public Nullable<int> mGroupMasterId { get; set; }
        public Nullable<int> mIteamTypeMasterId { get; set; }
        public Nullable<int> mSiteMasterId { get; set; }
        public Nullable<int> mZoneId { get; set; }
        public Nullable<int> mFloorMasterId { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public string img { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
