//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssetStockIssue
    {
        public int tAssetStockIssueId { get; set; }
        public Nullable<int> tAssetTagId { get; set; }
        public string UID { get; set; }
        public string RFID { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public string IssuedTo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
