//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_EmailConfiguration
    {
        public int EmailConfigurationId { get; set; }
        public string FromEmailId { get; set; }
        public string EmailServerName { get; set; }
        public string FromName { get; set; }
        public string LoginPassword { get; set; }
        public int Port { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
