//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmployeeTag
    {
        public int tEmployeeTagId { get; set; }
        public string RFID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<int> mAgencyId { get; set; }
        public Nullable<int> mDesignationId { get; set; }
        public Nullable<int> mSkillCategoryId { get; set; }
        public Nullable<int> mWorkCategoryId { get; set; }
        public Nullable<int> mActivityId { get; set; }
        public Nullable<int> mShiftId { get; set; }
        public Nullable<int> mSiteMasterId { get; set; }
        public Nullable<int> mZoneId { get; set; }
        public Nullable<int> mFloorMasterId { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
