//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toTooltag
    {
        public int toTooltagId { get; set; }
        public string ToolName { get; set; }
        public string Code { get; set; }
        public string BarCode { get; set; }
        public string RFID { get; set; }
        public string UID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string ModelNo { get; set; }
        public string Serial { get; set; }
        public string Size { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public string IteamStatus { get; set; }
        public string drawer { get; set; }
        public string drawerrack { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public Nullable<int> mUnitMasterId { get; set; }
        public Nullable<int> mIteamTypeMasterId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> bStock { get; set; }
        public Nullable<int> toSupplierId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
