//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toTrackInfo
    {
        public int toTrackInfoId { get; set; }
        public string RFID { get; set; }
        public string UID { get; set; }
        public string AppUserName { get; set; }
        public Nullable<int> mFloorMasterId { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public Nullable<int> mAttPortId { get; set; }
        public string ReaderIP { get; set; }
        public string ReaderNo { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public string RSSI { get; set; }
    }
}
