//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Log.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSpeedTrack
    {
        public int tSpeedTrackId { get; set; }
        public string Epc { get; set; }
        public Nullable<int> PortId { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
    }
}
