//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int AppUserId { get; set; }
        public string EMail { get; set; }
        public string AppUserName { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<int> AppRoleId { get; set; }
        public string Password { get; set; }
        public string Theme { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public string AccessLocation { get; set; }
        public Nullable<int> WorkingLocation { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string Mobile { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public bool IsFirstTimeLoggedIn { get; set; }
        public string UniqueId { get; set; }
        public Nullable<short> TodaysCallCount { get; set; }
        public string PwdRecoveryEmail { get; set; }
        public Nullable<int> LoginFailedAttempt { get; set; }
        public Nullable<System.DateTime> LoginFailedAttemptDuration { get; set; }
        public bool IsAllowed { get; set; }
    
        public virtual AppRole AppRole { get; set; }
    }
}
