//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCalibration
    {
        public int Id { get; set; }
        public Nullable<int> AssetMasterId { get; set; }
        public string AssetId { get; set; }
        public string AssetName { get; set; }
        public string CertificateNo { get; set; }
        public Nullable<System.DateTime> CalibrationDate { get; set; }
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public string Result { get; set; }
        public string Agency { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
