//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HexaModule
    {
        public int moduleID { get; set; }
        public string moduleName { get; set; }
        public string modulepath { get; set; }
        public string icon { get; set; }
        public string description { get; set; }
        public Nullable<bool> IsAction { get; set; }
    }
}
