//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMailConfig
    {
        public int mMailConfigId { get; set; }
        public string EmailId { get; set; }
        public string EmailServer { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public int Port { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> IsModify { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsNotify { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
