//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERPdbEntities : DbContext
    {
        public ERPdbEntities()
            : base("name=ERPdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppRole> AppRoles { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<ConfigureModel> ConfigureModels { get; set; }
        public virtual DbSet<DepartMent> DepartMents { get; set; }
        public virtual DbSet<HexaModule> HexaModules { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
        public virtual DbSet<mActivity> mActivities { get; set; }
        public virtual DbSet<mAgency> mAgencies { get; set; }
        public virtual DbSet<mDesignation> mDesignations { get; set; }
        public virtual DbSet<mEmployeeJobOrder> mEmployeeJobOrders { get; set; }
        public virtual DbSet<mEmployeeZone> mEmployeeZones { get; set; }
        public virtual DbSet<mFloorMaster> mFloorMasters { get; set; }
        public virtual DbSet<mGroupMaster> mGroupMasters { get; set; }
        public virtual DbSet<mIndooMap> mIndooMaps { get; set; }
        public virtual DbSet<mIteamMaster> mIteamMasters { get; set; }
        public virtual DbSet<mIteamTypeMaster> mIteamTypeMasters { get; set; }
        public virtual DbSet<mLocationMaster> mLocationMasters { get; set; }
        public virtual DbSet<mLocatorMaster> mLocatorMasters { get; set; }
        public virtual DbSet<mMailConfig> mMailConfigs { get; set; }
        public virtual DbSet<mMaintenanceType> mMaintenanceTypes { get; set; }
        public virtual DbSet<mReader> mReaders { get; set; }
        public virtual DbSet<mReaderSettup> mReaderSettups { get; set; }
        public virtual DbSet<mRoomMaster> mRoomMasters { get; set; }
        public virtual DbSet<mSetDistance> mSetDistances { get; set; }
        public virtual DbSet<mShelf> mShelves { get; set; }
        public virtual DbSet<mShift> mShifts { get; set; }
        public virtual DbSet<mSiteMaster> mSiteMasters { get; set; }
        public virtual DbSet<mSkillCategory> mSkillCategories { get; set; }
        public virtual DbSet<mSMTProduct> mSMTProducts { get; set; }
        public virtual DbSet<mStatusMaster> mStatusMasters { get; set; }
        public virtual DbSet<mSupplier> mSuppliers { get; set; }
        public virtual DbSet<mUnitMaster> mUnitMasters { get; set; }
        public virtual DbSet<mVendor> mVendors { get; set; }
        public virtual DbSet<mWarehouseMaster> mWarehouseMasters { get; set; }
        public virtual DbSet<mWorkCategory> mWorkCategories { get; set; }
        public virtual DbSet<mWorkOrder> mWorkOrders { get; set; }
        public virtual DbSet<mZone> mZones { get; set; }
        public virtual DbSet<OrgInfo> OrgInfoes { get; set; }
        public virtual DbSet<RoleAcess> RoleAcesses { get; set; }
        public virtual DbSet<RoleMenu> RoleMenus { get; set; }
        public virtual DbSet<Rolemodule> Rolemodules { get; set; }
        public virtual DbSet<SmtProductAuditLog> SmtProductAuditLogs { get; set; }
        public virtual DbSet<tAssetCheckOut> tAssetCheckOuts { get; set; }
        public virtual DbSet<tAssetMonitor> tAssetMonitors { get; set; }
        public virtual DbSet<tAssetStockIn> tAssetStockIns { get; set; }
        public virtual DbSet<tAssetStockIssue> tAssetStockIssues { get; set; }
        public virtual DbSet<tAssetStockTranfer> tAssetStockTranfers { get; set; }
        public virtual DbSet<tAssetTag> tAssetTags { get; set; }
        public virtual DbSet<TC_Action> TC_Action { get; set; }
        public virtual DbSet<TC_Customer> TC_Customer { get; set; }
        public virtual DbSet<TC_EmailConfiguration> TC_EmailConfiguration { get; set; }
        public virtual DbSet<TC_InquiryGroupSource> TC_InquiryGroupSource { get; set; }
        public virtual DbSet<TC_InquirySource> TC_InquirySource { get; set; }
        public virtual DbSet<TC_InquiryStatus> TC_InquiryStatus { get; set; }
        public virtual DbSet<TC_InquiryType> TC_InquiryType { get; set; }
        public virtual DbSet<TC_Lead> TC_Lead { get; set; }
        public virtual DbSet<TC_LeadDisposition> TC_LeadDisposition { get; set; }
        public virtual DbSet<TC_LeadFollowUp> TC_LeadFollowUp { get; set; }
        public virtual DbSet<TC_LeadStage> TC_LeadStage { get; set; }
        public virtual DbSet<TC_LeadSubDisposition> TC_LeadSubDisposition { get; set; }
        public virtual DbSet<TC_LeadType> TC_LeadType { get; set; }
        public virtual DbSet<tEmployeeTag> tEmployeeTags { get; set; }
        public virtual DbSet<tExtendWarranty> tExtendWarranties { get; set; }
        public virtual DbSet<tMaintenance> tMaintenances { get; set; }
        public virtual DbSet<toCategoryMaster> toCategoryMasters { get; set; }
        public virtual DbSet<toMonitor> toMonitors { get; set; }
        public virtual DbSet<toRFIDType> toRFIDTypes { get; set; }
        public virtual DbSet<toSupplier> toSuppliers { get; set; }
        public virtual DbSet<toSupplierCategory> toSupplierCategories { get; set; }
        public virtual DbSet<toSupplierType> toSupplierTypes { get; set; }
        public virtual DbSet<toToolMaintenance> toToolMaintenances { get; set; }
        public virtual DbSet<toToolStockIn> toToolStockIns { get; set; }
        public virtual DbSet<toTooltag> toTooltags { get; set; }
        public virtual DbSet<toTrackInfo> toTrackInfoes { get; set; }
        public virtual DbSet<tPortChangeLog> tPortChangeLogs { get; set; }
        public virtual DbSet<tReaderLog> tReaderLogs { get; set; }
        public virtual DbSet<tRFIDType> tRFIDTypes { get; set; }
        public virtual DbSet<tSpeedTrack> tSpeedTracks { get; set; }
        public virtual DbSet<tToolTrackDemo> tToolTrackDemoes { get; set; }
        public virtual DbSet<tTrackInfo> tTrackInfoes { get; set; }
        public virtual DbSet<mEmployeeJobOrderAudit> mEmployeeJobOrderAudits { get; set; }
        public virtual DbSet<AssetCalibration> AssetCalibrations { get; set; }
        public virtual DbSet<AssetInspection> AssetInspections { get; set; }
        public virtual DbSet<tAssetCalibration> tAssetCalibrations { get; set; }
        public virtual DbSet<tAssetMaintenance> tAssetMaintenances { get; set; }
        public virtual DbSet<tAssetInspection> tAssetInspections { get; set; }
        public virtual DbSet<mAssetSubCategory2> mAssetSubCategory2 { get; set; }
    
        public virtual ObjectResult<proDistance_Result> proDistance(Nullable<int> startPort, Nullable<int> endPort)
        {
            var startPortParameter = startPort.HasValue ?
                new ObjectParameter("StartPort", startPort) :
                new ObjectParameter("StartPort", typeof(int));
    
            var endPortParameter = endPort.HasValue ?
                new ObjectParameter("EndPort", endPort) :
                new ObjectParameter("EndPort", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proDistance_Result>("proDistance", startPortParameter, endPortParameter);
        }
    
        public virtual ObjectResult<proToolsTrackReport_Result> proToolsTrackReport(Nullable<System.DateTime> toDate, Nullable<System.DateTime> fromDate)
        {
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proToolsTrackReport_Result>("proToolsTrackReport", toDateParameter, fromDateParameter);
        }
    
        public virtual ObjectResult<string> spCrateLead(string uid, string name, string lastName, string gender, string emailId, string contact, string address, string city, string state, Nullable<int> pinCode)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("Uid", uid) :
                new ObjectParameter("Uid", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var pinCodeParameter = pinCode.HasValue ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCrateLead", uidParameter, nameParameter, lastNameParameter, genderParameter, emailIdParameter, contactParameter, addressParameter, cityParameter, stateParameter, pinCodeParameter);
        }
    
        public virtual ObjectResult<spEmployeeAtt_Result> spEmployeeAtt(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmployeeAtt_Result>("spEmployeeAtt", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spEmployeeTrackReport_Result> spEmployeeTrackReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spEmployeeTrackReport_Result>("spEmployeeTrackReport", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<spGerReaderSetting_Result> spGerReaderSetting()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGerReaderSetting_Result>("spGerReaderSetting");
        }
    
        public virtual ObjectResult<spReportSummary_Result> spReportSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spReportSummary_Result>("spReportSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual int spEmployeeReportSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEmployeeReportSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spNewReportSummary_Result> spNewReportSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewReportSummary_Result>("spNewReportSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual int spEmployeeTrackSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEmployeeTrackSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual int spNewEmployeeTrackSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spNewEmployeeTrackSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spNewTrackSummaryEmployee_Result> spNewTrackSummaryEmployee(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewTrackSummaryEmployee_Result>("spNewTrackSummaryEmployee", fromDateParameter, toDateParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spTrackSummary_Result> spTrackSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTrackSummary_Result>("spTrackSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spNewTrackSummary_Result> spNewTrackSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewTrackSummary_Result>("spNewTrackSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spZoneReportSummary_Result> spZoneReportSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spZoneReportSummary_Result>("spZoneReportSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spNewZoneReportSummary_Result> spNewZoneReportSummary(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewZoneReportSummary_Result>("spNewZoneReportSummary", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spNewReportSummaryZone_Result> spNewReportSummaryZone(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spNewReportSummaryZone_Result>("spNewReportSummaryZone", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spGetCountRecord_Result> spGetCountRecord(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetCountRecord_Result>("spGetCountRecord", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<EmployeeAttCounts_Result> EmployeeAttCounts(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmployeeAttCounts_Result>("EmployeeAttCounts", fromDateParameter, toDateParameter);
        }
    
        public virtual int spTrendHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTrendHours");
        }
    
        public virtual int sp_TrendHours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TrendHours");
        }
    
        public virtual ObjectResult<spTrendsHour_Result> spTrendsHour()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTrendsHour_Result>("spTrendsHour");
        }
    
        public virtual ObjectResult<spSiteTimeSpend_Result> spSiteTimeSpend(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSiteTimeSpend_Result>("spSiteTimeSpend", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spAssetDepreciation_Result> spAssetDepreciation(Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mRoomMasterId, Nullable<int> mGroupMasterId, Nullable<int> mIteamTypeMasterId, Nullable<int> mIteamMasterId, Nullable<int> mVendorId, string barCode, string uID, Nullable<int> mStatusMasterId)
        {
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mRoomMasterIdParameter = mRoomMasterId.HasValue ?
                new ObjectParameter("mRoomMasterId", mRoomMasterId) :
                new ObjectParameter("mRoomMasterId", typeof(int));
    
            var mGroupMasterIdParameter = mGroupMasterId.HasValue ?
                new ObjectParameter("mGroupMasterId", mGroupMasterId) :
                new ObjectParameter("mGroupMasterId", typeof(int));
    
            var mIteamTypeMasterIdParameter = mIteamTypeMasterId.HasValue ?
                new ObjectParameter("mIteamTypeMasterId", mIteamTypeMasterId) :
                new ObjectParameter("mIteamTypeMasterId", typeof(int));
    
            var mIteamMasterIdParameter = mIteamMasterId.HasValue ?
                new ObjectParameter("mIteamMasterId", mIteamMasterId) :
                new ObjectParameter("mIteamMasterId", typeof(int));
    
            var mVendorIdParameter = mVendorId.HasValue ?
                new ObjectParameter("mVendorId", mVendorId) :
                new ObjectParameter("mVendorId", typeof(int));
    
            var barCodeParameter = barCode != null ?
                new ObjectParameter("BarCode", barCode) :
                new ObjectParameter("BarCode", typeof(string));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            var mStatusMasterIdParameter = mStatusMasterId.HasValue ?
                new ObjectParameter("mStatusMasterId", mStatusMasterId) :
                new ObjectParameter("mStatusMasterId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAssetDepreciation_Result>("spAssetDepreciation", mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mRoomMasterIdParameter, mGroupMasterIdParameter, mIteamTypeMasterIdParameter, mIteamMasterIdParameter, mVendorIdParameter, barCodeParameter, uIDParameter, mStatusMasterIdParameter);
        }
    
        public virtual ObjectResult<spAssetReport_Result> spAssetReport(Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mRoomMasterId, Nullable<int> mGroupMasterId, Nullable<int> mIteamTypeMasterId, Nullable<int> mIteamMasterId, Nullable<int> mVendorId, string barCode, string uID, Nullable<int> mStatusMasterId)
        {
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mRoomMasterIdParameter = mRoomMasterId.HasValue ?
                new ObjectParameter("mRoomMasterId", mRoomMasterId) :
                new ObjectParameter("mRoomMasterId", typeof(int));
    
            var mGroupMasterIdParameter = mGroupMasterId.HasValue ?
                new ObjectParameter("mGroupMasterId", mGroupMasterId) :
                new ObjectParameter("mGroupMasterId", typeof(int));
    
            var mIteamTypeMasterIdParameter = mIteamTypeMasterId.HasValue ?
                new ObjectParameter("mIteamTypeMasterId", mIteamTypeMasterId) :
                new ObjectParameter("mIteamTypeMasterId", typeof(int));
    
            var mIteamMasterIdParameter = mIteamMasterId.HasValue ?
                new ObjectParameter("mIteamMasterId", mIteamMasterId) :
                new ObjectParameter("mIteamMasterId", typeof(int));
    
            var mVendorIdParameter = mVendorId.HasValue ?
                new ObjectParameter("mVendorId", mVendorId) :
                new ObjectParameter("mVendorId", typeof(int));
    
            var barCodeParameter = barCode != null ?
                new ObjectParameter("BarCode", barCode) :
                new ObjectParameter("BarCode", typeof(string));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            var mStatusMasterIdParameter = mStatusMasterId.HasValue ?
                new ObjectParameter("mStatusMasterId", mStatusMasterId) :
                new ObjectParameter("mStatusMasterId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAssetReport_Result>("spAssetReport", mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mRoomMasterIdParameter, mGroupMasterIdParameter, mIteamTypeMasterIdParameter, mIteamMasterIdParameter, mVendorIdParameter, barCodeParameter, uIDParameter, mStatusMasterIdParameter);
        }
    
        public virtual ObjectResult<spAssetWithEmployee_Result> spAssetWithEmployee(Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mRoomMasterId, Nullable<int> mGroupMasterId, Nullable<int> mIteamTypeMasterId, Nullable<int> mIteamMasterId, Nullable<int> mVendorId, string barCode, string uID, Nullable<int> mStatusMasterId, Nullable<int> tEmployeeTagId)
        {
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mRoomMasterIdParameter = mRoomMasterId.HasValue ?
                new ObjectParameter("mRoomMasterId", mRoomMasterId) :
                new ObjectParameter("mRoomMasterId", typeof(int));
    
            var mGroupMasterIdParameter = mGroupMasterId.HasValue ?
                new ObjectParameter("mGroupMasterId", mGroupMasterId) :
                new ObjectParameter("mGroupMasterId", typeof(int));
    
            var mIteamTypeMasterIdParameter = mIteamTypeMasterId.HasValue ?
                new ObjectParameter("mIteamTypeMasterId", mIteamTypeMasterId) :
                new ObjectParameter("mIteamTypeMasterId", typeof(int));
    
            var mIteamMasterIdParameter = mIteamMasterId.HasValue ?
                new ObjectParameter("mIteamMasterId", mIteamMasterId) :
                new ObjectParameter("mIteamMasterId", typeof(int));
    
            var mVendorIdParameter = mVendorId.HasValue ?
                new ObjectParameter("mVendorId", mVendorId) :
                new ObjectParameter("mVendorId", typeof(int));
    
            var barCodeParameter = barCode != null ?
                new ObjectParameter("BarCode", barCode) :
                new ObjectParameter("BarCode", typeof(string));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            var mStatusMasterIdParameter = mStatusMasterId.HasValue ?
                new ObjectParameter("mStatusMasterId", mStatusMasterId) :
                new ObjectParameter("mStatusMasterId", typeof(int));
    
            var tEmployeeTagIdParameter = tEmployeeTagId.HasValue ?
                new ObjectParameter("tEmployeeTagId", tEmployeeTagId) :
                new ObjectParameter("tEmployeeTagId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAssetWithEmployee_Result>("spAssetWithEmployee", mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mRoomMasterIdParameter, mGroupMasterIdParameter, mIteamTypeMasterIdParameter, mIteamMasterIdParameter, mVendorIdParameter, barCodeParameter, uIDParameter, mStatusMasterIdParameter, tEmployeeTagIdParameter);
        }
    
        public virtual int spGetAssetInfo(string rFID, string barCode, string iteamName, string model, string modelNo, string uID)
        {
            var rFIDParameter = rFID != null ?
                new ObjectParameter("RFID", rFID) :
                new ObjectParameter("RFID", typeof(string));
    
            var barCodeParameter = barCode != null ?
                new ObjectParameter("BarCode", barCode) :
                new ObjectParameter("BarCode", typeof(string));
    
            var iteamNameParameter = iteamName != null ?
                new ObjectParameter("IteamName", iteamName) :
                new ObjectParameter("IteamName", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var modelNoParameter = modelNo != null ?
                new ObjectParameter("ModelNo", modelNo) :
                new ObjectParameter("ModelNo", typeof(string));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetAssetInfo", rFIDParameter, barCodeParameter, iteamNameParameter, modelParameter, modelNoParameter, uIDParameter);
        }
    
        public virtual ObjectResult<spGetEmployeeForWork_Result> spGetEmployeeForWork(string employeeName, string employeeId)
        {
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetEmployeeForWork_Result>("spGetEmployeeForWork", employeeNameParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<spZoneTimeSpend_Result> spZoneTimeSpend(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> mSiteMasterId, Nullable<int> mZoneId, Nullable<int> mFloorMasterId, Nullable<int> mAgencyId, Nullable<int> mDesignationId, Nullable<int> mSkillCategoryId, Nullable<int> mWorkCategoryId, Nullable<int> mActivityId, string employeeName, string employeeId)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var mSiteMasterIdParameter = mSiteMasterId.HasValue ?
                new ObjectParameter("mSiteMasterId", mSiteMasterId) :
                new ObjectParameter("mSiteMasterId", typeof(int));
    
            var mZoneIdParameter = mZoneId.HasValue ?
                new ObjectParameter("mZoneId", mZoneId) :
                new ObjectParameter("mZoneId", typeof(int));
    
            var mFloorMasterIdParameter = mFloorMasterId.HasValue ?
                new ObjectParameter("mFloorMasterId", mFloorMasterId) :
                new ObjectParameter("mFloorMasterId", typeof(int));
    
            var mAgencyIdParameter = mAgencyId.HasValue ?
                new ObjectParameter("mAgencyId", mAgencyId) :
                new ObjectParameter("mAgencyId", typeof(int));
    
            var mDesignationIdParameter = mDesignationId.HasValue ?
                new ObjectParameter("mDesignationId", mDesignationId) :
                new ObjectParameter("mDesignationId", typeof(int));
    
            var mSkillCategoryIdParameter = mSkillCategoryId.HasValue ?
                new ObjectParameter("mSkillCategoryId", mSkillCategoryId) :
                new ObjectParameter("mSkillCategoryId", typeof(int));
    
            var mWorkCategoryIdParameter = mWorkCategoryId.HasValue ?
                new ObjectParameter("mWorkCategoryId", mWorkCategoryId) :
                new ObjectParameter("mWorkCategoryId", typeof(int));
    
            var mActivityIdParameter = mActivityId.HasValue ?
                new ObjectParameter("mActivityId", mActivityId) :
                new ObjectParameter("mActivityId", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var employeeIdParameter = employeeId != null ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spZoneTimeSpend_Result>("spZoneTimeSpend", fromDateParameter, toDateParameter, mSiteMasterIdParameter, mZoneIdParameter, mFloorMasterIdParameter, mAgencyIdParameter, mDesignationIdParameter, mSkillCategoryIdParameter, mWorkCategoryIdParameter, mActivityIdParameter, employeeNameParameter, employeeIdParameter);
        }
    }
}
