//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mReaderSettup
    {
        public int mReaderSettupId { get; set; }
        public Nullable<int> mSiteMasterId { get; set; }
        public Nullable<int> mZoneId { get; set; }
        public Nullable<int> mFloorMasterId { get; set; }
        public Nullable<int> mIndooMapsId { get; set; }
        public string UID { get; set; }
        public Nullable<int> Xaxis { get; set; }
        public Nullable<int> Yaxis { get; set; }
        public Nullable<int> mRoomMasterId { get; set; }
        public string ReaderNo { get; set; }
        public string ReaderIP { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
        public Nullable<int> AttPortId { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
