//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSetDistance
    {
        public int mSetDistanceId { get; set; }
        public Nullable<int> StartPort { get; set; }
        public Nullable<int> EndPort { get; set; }
        public Nullable<decimal> Distance { get; set; }
    }
}
