//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAcess
    {
        public int RoleAcessId { get; set; }
        public Nullable<int> RoleMenuId { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<int> AppMenuId { get; set; }
        public Nullable<int> AppUserId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> Iswrite { get; set; }
        public Nullable<bool> IsModifiy { get; set; }
        public Nullable<bool> IsSuperUser { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
