//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmtProductAuditLog
    {
        public long mSMTProductId { get; set; }
        public string OldRowData { get; set; }
        public string NewRowData { get; set; }
        public string DmlType { get; set; }
        public System.DateTime DmlTimestamp { get; set; }
        public string DmlCreatedBy { get; set; }
        public System.DateTime TrxTimestamp { get; set; }
    }
}
