//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssetInspection
    {
        public int AssetInspectionId { get; set; }
        public int AssetId { get; set; }
        public string AssetName { get; set; }
        public string InspectionNo { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public string Inspector { get; set; }
        public string PhysicalCondition { get; set; }
        public string SafetyLabels { get; set; }
        public string FitForUse { get; set; }
        public string Observation { get; set; }
        public string Status { get; set; }
        public bool IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual mIteamMaster mIteamMaster { get; set; }
    }
}
