//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssetCalibration
    {
        public int AssetCalibrationId { get; set; }
        public int AssetId { get; set; }
        public string AssetName { get; set; }
        public string CertificateNo { get; set; }
        public System.DateTime CalibrationDate { get; set; }
        public Nullable<System.DateTime> NextDueDate { get; set; }
        public string Result { get; set; }
        public string Agency { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public bool IsAction { get; set; }
        public int OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual mIteamMaster mIteamMaster { get; set; }
    }
}
