//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssetMaintenance
    {
        public int AssetMaintenanceId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string WorkOrderNo { get; set; }
        public string AssetName { get; set; }
        public string MaintenanceType { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TargetClosure { get; set; }
        public string Technician { get; set; }
        public Nullable<decimal> DowntimeHours { get; set; }
        public string Scope { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual mIteamMaster mIteamMaster { get; set; }
    }
}
