//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_Action
    {
        public int TC_ActionId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string ActionName { get; set; }
        public string PreActionCall { get; set; }
        public string PostActionCall { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> OrgInfoID { get; set; }
    }
}
