//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_InquirySource
    {
        public int TC_InquirySourceId { get; set; }
        public string Source { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<byte> OrderBy { get; set; }
        public Nullable<short> TC_InquiryGroupSourceId { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
