//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_Lead
    {
        public long TC_LeadId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<int> TC_InquirySourceId { get; set; }
        public Nullable<byte> TC_LeadStageId { get; set; }
        public Nullable<int> TC_InquiryTypeId { get; set; }
        public Nullable<int> TC_InquiryStatusId { get; set; }
        public Nullable<System.DateTime> LeadVerificationDate { get; set; }
        public Nullable<int> LeadVerifiedBy { get; set; }
        public Nullable<System.DateTime> LeadCreationDate { get; set; }
        public Nullable<System.DateTime> LeadClosedDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> LeadType { get; set; }
        public Nullable<int> TC_LeadDispositionId { get; set; }
        public Nullable<int> TC_CampaignSchedulingId { get; set; }
        public Nullable<int> TC_ActionId { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public string NextFollowUpAssinged { get; set; }
        public string PreActionCall { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> OrgInfoID { get; set; }
    }
}
