//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tExtendWarranty
    {
        public int tExtendWarrantyId { get; set; }
        public Nullable<int> tAssetTagId { get; set; }
        public Nullable<int> NoOfMonths { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsAction { get; set; }
        public Nullable<int> OrgInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
