//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toMonitor
    {
        public int Id { get; set; }
        public string Epc { get; set; }
        public Nullable<int> AntennaPortNumber { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime tDate { get; set; }
        public string RSSI { get; set; }
        public string LastSeenTime { get; set; }
        public Nullable<System.DateTime> LastSeenTime2 { get; set; }
        public string BatteryLevel { get; set; }
    }
}
