//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HexaERP.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRFIDType
    {
        public int tRFIDTypesId { get; set; }
        public Nullable<int> RerfrenceId { get; set; }
        public string RFID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<bool> Type { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsAction { get; set; }
    }
}
